# spring configuration
spring:
   application:
      name: mysite
      
   #devtools - live reload
   devtools:
      livereload:
         enabled: true   
      
   #aop
   aop:
      auto: true
      proxy-target-class: true
      
   #mvc      
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   
   #datasource      
   datasource:
      dirver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.64.10:3306/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
         
#mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
   
      
# server configuration
server:
   port: 8080
   servlet:
      context-path: /mysite6
      encoding:
         charset: utf-8
         enabled: true
         
#loggin
logging:
   config: classpath:logback.xml
   